### ISSUE TITLE
Can I sync faster using another node?

### ISSUE THREAD

**Issue by heartache4** [sunnyside-io/op-erigon#115]
I have a local OP mainnet op-geth node and would like to sync an OP mainnet op-erigon node faster, since at about 5 blocks per second it's going to take over a month to sync from the Bedrock snapshot. Is there any way to take advantage of my op-geth node in this way? I know on the Ethereum mainnet, you can add another local node as a peer to help speed up block downloading. I wonder if the same can be done here somehow.

I tried adding my op-geth node as a static peer to op-erigon, but it would not connect to my op-geth node (I tried enabling peers again, but still it would not connect). I also tried adding my op-node (for op-geth) as a peer to my op-node (for op-erigon), and although they were connected they were only transferring like 1KB per second to each other, so that did not speed things up.

Is it some kind of limitation of the Optimism block download architecture? I don't really know how blocks are delivered so maybe I am missing something. Providing a more recent snapshot could also be a nice shortcut too.

**Comment by taempark** [comment]
Hi @heartache4! Generally, you can sync faster with Engine Sync—i.e., snap sync. But it's currently WIP. The default syncing option is deriving L2 blocks from L1, which isn't fast as it requires reading whole L1 blocks.

We built a tool that syncs your L2 node by receiving blocks from other L2 nodes: [op-fast-sync](https://github.com/testinprod-io/op-fast-sync). Apologies for missing documentation, but the required parameters are quite intuitive; please refer to the main.py.

**Comment by heartache4** [comment]
Thank you! At first I got `--rpc` and `--l2` arguments mixed up, but after trial and error I figured it out. Is it normal that op-fast-sync builds a huge payload like `building payload | 155654/5692249 | elapsed: 00:02:40`?

**Comment by taempark** [comment]
Hmm. Not sure about that. Can you make an issue in the op-fast-sync repository?

**Comment by heartache4** [comment]
After several hours it created all the payloads (millions of files in the payload directory) after which it began applying them to the op-erigon node (`applying payload | ...`). It is able to sync at about 17 blocks per second after that on my computer. This is much improved over standard syncing via op-node. Thank you for providing the solution!

Also if others find this issue: `--rpc` is for the RPC of the target node you want to sync. `--l2` is for the source OP node you get the block data from.
