### ISSUE TITLE
Implement `engine_signalSuperchainV1`

### ISSUE THREAD

**Issue by pcw109550** [sunnyside-io/op-erigon#119]
Mirror https://github.com/ethereum-optimism/op-geth/pull/128.
Spec: https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/exec-engine.md#engine_signalsuperchainv1

**Comment by pcw109550** [comment]
For context; Its basically a rephrase of the description of https://github.com/ethereum-optimism/op-geth/pull/128.

OP-stack has two major components. One is the consensus layer(op-node), and other is execution layer(op-erigon or op-geth). You can think that each component is a separate service, or server. Consensus layer is the controller. It _controlls_ execution layer by calling APIs. Refer to the below diagram([Ref](https://docs.optimism.io/builders/node-operators/overview#diagram)). In our case, op-geth is substituted to op-erigon:

![image](https://github.com/testinprod-io/op-erigon/assets/29061389/87d1c8f3-2d66-4216-96ab-653333a495da)


Each server has their own version. Two servers communicate, and each expects that the counterparty has valid version for communication. It is recommended to early terminate the connection when version mismatches; there is no point to trying to communicate when protocol mismatches.

The API `engine_signalSuperchainV1` is implemented for this kind of version communication. When consensus layer starts, it first asks the execution layer that it has a compatible version. If yes, communication continues. Warn if execution layer is compatible but not having the recommended version. If not, early terminate everything. 

This issue asks to implement `engine_signalSuperchainV1` to op-erigon, as [this PR](https://github.com/ethereum-optimism/op-geth/pull/128) did to op-geth. op-erigon must correctly implement the API based on the [specs](https://github.com/ethereum-optimism/specs/blob/main/specs/protocol/exec-engine.md#engine_signalsuperchainv1)

**Comment by mininny** [comment]
Implemented in https://github.com/testinprod-io/op-erigon/pull/148
