### ISSUE TITLE
Canyon hard-fork stucks

### ISSUE THREAD

**Issue by R4ZN1V** [sunnyside-io/op-erigon#120]
Our nodes were stuck after the Canyon hard-fork. We've used the `itegration` binary to unwind back, but everytime we're getting to the block were the hard-fork was done, we're getting stuck (specifically on Base).
Would love some help here.
Attached error from our Base op-erigon node:
```wrong head block                         current=0x570ff94038b3733f0219180341fe9923ef9d1dd4bc184e6e67e927d2db80db09 requested=0x32262b8baccc3966d98b57eef14a34db9261101abce7424598cbeade13e75378 executionAt=9101526```

**Comment by pcw109550** [comment]
Please provide op-node logs, op-erigon logs, and their versions.

**Comment by pc-quiknode** [comment]
Our node is stuck at block [114696811](https://optimistic.etherscan.io/block/114696811)

Seeing this error from op-node v1.4.2
```
lvl=warn msg="Derivation process temporary error"     attempts=30820 err="engine stage failed: temp: temporarily cannot insert new safe block: failed to create new block via forkchoice: unrecognized rpc error: withdrawals before shanghai"
```

and op-erigon
```
method=engine_forkchoiceUpdatedV2 reqid=33955 t=300.218µs err="withdrawals before shanghai"
```

**Comment by sbvegan** [comment]
I'm pretty sure you're going to need to clear your database and resync to recover these nodes

**Comment by pcw109550** [comment]
@pc-quiknode 
This means op-erigon is not yet aware of canyon. You may fix this by using the most recent version(https://github.com/testinprod-io/op-erigon/releases/tag/v2.51.0-0.3.1) of op-erigon.

I think you do not have to resync in this case, because the db was not altered because forkchoiceupdate RPC call failed. Updating op-erigon may be fine.
