### ISSUE TITLE
Historical info of pre-bedrock blocks is missing

### ISSUE THREAD

**Issue by darkxeno** [sunnyside-io/op-erigon#134]
hello, is there a way to get historical / archive information about pre-bedrock blocks?

We get an 403 error when trying to do so, is there an archive snapshot that we can use for this?

Error example below:

```
request:
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"debug_traceBlockByNumber","params":["0x64602f", {"tracer": "callTracer"}],"id":1}' http://localhost:8545/

response:
{"jsonrpc":"2.0","id":1,"result":null,"error":{"code":-32000,"message":"historical backend error: 403 Forbidden: {\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32001,\"message\":\"rpc method is not whitelisted\"},\"id\":7}\n"}}
```

Thank you so much

**Comment by pcw109550** [comment]
OP-erigon does not support prebedrock blocks. You must use l2geth with legacy snapshot. Please refer to https://docs.optimism.io/builders/node-operators/tutorials/mainnet#start-legacy-geth-optional.
