### ISSUE TITLE
Test stage sync with op-node's execution-layer sync mode

### ISSUE THREAD

**Issue by ImTei** [sunnyside-io/op-erigon#147]
In the op-node [v1.7.0](https://github.com/ethereum-optimism/optimism/tree/v1.7.0), experimental execution-layer sync mode was added. We should test if this works with op-erigon stage sync.

**Comment by mininny** [comment]
Completed with guide for staged sync on https://github.com/testinprod-io/op-erigon?tab=readme-ov-file#execution-layer-syncing
