### ISSUE TITLE
Information request

### ISSUE THREAD

**Issue by 0xChupaCabra** [sunnyside-io/op-erigon#158]
Hello, may i know the size of an op archive node using this client?
Thanks

**Comment by ImTei** [comment]
@0xChupaCabra You can download the latest DB snapshot of OP mainnet from https://snapshot.testinprod.io.
Note that the size is compressed size. you should download and decompress it to get the actual DB size.

**Comment by 0xChupaCabra** [comment]
I was looking to know the full size of a sync'ed node. I will just try it. Thanks!
