### ISSUE TITLE
Incorrect effectiveGasPrice in receipt

### ISSUE THREAD

**Issue by quickchase** [sunnyside-io/op-erigon#159]
`erigon version 0.05.0-2.55.1`

On Optimism Mainnet the following transaction has the incorrect "effectiveGasPrice"

```json
{"jsonrpc":"2.0","id":1,"method":"eth_getTransactionReceipt","params":["0xd8fca681d83ef12ebf44a31dafad3431b5cfcb8f7490851c8d4337085a99a38d"]}
```

Op-Erigon is returning: `"effectiveGasPrice": "0x3d7b56f"`

Op-Geth is returning: `"effectiveGasPrice": "0x0",`

Based on the explanation from the Optimism team:
> it was a deposit-transaction (i.e. no signature, generated by system as part of upgrade), so no gas is paid in L2, and so the price should be 0 [...] op-erigon for some reason implies that deposits pay gas on L2, whereas they don't. Likely some receipt-hydration quirk/bug.

I don't have any nodes on `v2.56.2-0.5.0` to test with right now but I'll try to report back, if anyone can confirm that would be 🙏

**Comment by taempark** [comment]
^ @quickchase FYI

**Comment by ImTei** [comment]
released https://github.com/testinprod-io/op-erigon/releases/tag/v2.56.2-0.5.2!
