### ISSUE TITLE
net_version is incorrect

### ISSUE THREAD

**Issue by 86b** [sunnyside-io/op-erigon#188]
Branch `upstream-v2.60.1`

If you call `net_version` it returns `1` instead of `10`.  `eth_chainId` is good

**Comment by 86b** [comment]
this is also happening on `v2.60.1-0.6.3`

**Comment by ImTei** [comment]
@86b Did you set the `--chain=op-mainnet` flag?

**Comment by 86b** [comment]
@ImTei that was the fix... I didn't realize we needed that flag because I thought the default was `mainnet` as in OP Mainnet.  Thanks!
