### ISSUE TITLE
Cannot pull new multiplatform image from k8s

### ISSUE THREAD

**Issue by arnaudbriche** [sunnyside-io/op-erigon#221]
#### System information

Erigon version: `./erigon --version`

OS & Version: Windows/Linux/OSX

Commit hash: 

Erigon Command (with flags/config):

Consensus Layer:

Consensus Layer Command (with flags/config):

Chain/Network: 

#### Expected behaviour

When I tried to upgrade my k8s deployment with the latest multiplatform image, I get the following error:

```
Failed to pull image "testinprod/op-erigon:2.60.8-0.7.1": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/testinprod/op-erigon:2.60.8-0.7.1": no match for platform in manifest: not found
```

#### Actual behaviour

I would expect this to work fine.

#### Backtrace

````
[backtrace]
````

**Comment by mininny** [comment]
Hi @arnaudbriche Thanks for raising the issue :) What platform are you trying to pull the docker image for? Could you provide more information like your dockerfile or configurations?

**Comment by arnaudbriche** [comment]
Hi @mininny ,

My k8s cluster is deployed on linux amd64 nodes in a cloud.
I just pull the image locally and pushed it back to my docker hub account and it works now.

https://hub.docker.com/r/agnosticeng/op-erigon/tags

**Comment by mininny** [comment]
Glad to hear it's working :+1: Feel free to let us know when you encounter any other issues.
