### ISSUE TITLE
Missing environment variable in README

### ISSUE THREAD

**Issue by tjayrush** [sunnyside-io/op-erigon#55]
The environment variable `HISTORICAL_RPC_ENDPOINT` is used in the README, but no-where defined, so the end user does not know what value to set.

`HISTORICAL_RPC_ENDPOINT` is equal to the following flag: https://github.com/testinprod-io/op-erigon#--rolluphistoricalrpc

**Comment by pcw109550** [comment]
You may choose `HISTORICAL_RPC_ENDPOINT` between below three options.
1. Use testing RPC url: `https://goerli.optimism.io`
2. Use alchemy's goerli optimism RPC url.
3. Spin up your own l2geth and expose your l2geth url. Refer to https://community.optimism.io/docs/developers/bedrock/node-operator-guide/#legacy-geth for more details.

Will Update README to add these details.

**Comment by pcw109550** [comment]
https://github.com/testinprod-io/op-erigon/pull/69
